import logging
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from tests.utils.runtime_tracking import DEFAULT_SLOWEST_TESTS_LIMIT
from tests.utils.runtime_tracking import execute_test_suite
from tests.utils.cleanup import cleanup_csv_files
from tests.utils.cleanup import setup_cleanup_handlers
from tests.test_foundational_sfd import test_foundational_sfd
from tests.test_conserved_flux_renormalization import test_conserved_flux_renormalization
from tests.test_confidence_filtering_system import test_calibrate_confidence_threshold
from tests.test_confidence_filtering_system import test_apply_confidence_filtering
from tests.test_confidence_filtering_system import test_confidence_filtering_system
from tests.test_confidence_filtering_system import test_edge_cases
from tests.test_account_conviction import test_account_conviction
from tests.test_backtest_conviction import test_backtest_conviction
from tests.test_klines_data_maker_fields import test_klines_data_maker_fields
from tests.test_large_param_space import test_large_param_space
from tests.test_param_space import test_param_space_large_space_no_longer_overflows_and_is_reproducible
from tests.test_param_space import test_param_space_large_space_sequences_match_for_both_generation_modes
from tests.test_param_space import test_param_space_enumerates_full_space_and_returns_none_when_exhausted
from tests.test_param_space import test_param_space_small_legacy_sequence_is_unchanged
from tests.test_param_space import test_sample_range_exact_handles_edge_cases
from tests.test_param_space import test_sample_range_exact_matches_stdlib_and_preserves_rng_state
from tests.test_param_space import test_sample_range_exact_preserves_prefix_for_huge_ranges
from tests.test_param_space import test_sample_range_exact_retries_rejected_and_duplicate_draws_in_order
from tests.test_param_space import test_sample_range_exact_skips_small_range_fallback_above_sys_maxsize
from tests.test_bars import test_volume_bars_basic
from tests.test_bars import test_trade_bars_basic
from tests.test_bars import test_liquidity_bars_basic
from tests.test_bars import test_compute_data_bars_base_and_unknown_modes_return_input_unchanged
from tests.test_bars import test_compute_data_bars_dispatches_to_specific_bar_builders
from tests.test_bars import test_compute_data_bars_requires_threshold_for_selected_bar_type
from tests.test_manifest_pre_split_random_selector import test_pre_split_random_selector
from tests.test_regime_diversified_opinion_pools import test_rdop
from tests.test_regime_pools_helpers import test_offline_filter_sanity_filter_drops_rows_with_null_performance_values
from tests.test_regime_pools_helpers import test_offline_filter_outlier_filter_removes_extreme_iqr_outlier
from tests.test_regime_pools_helpers import test_offline_regime_cluster_models_returns_single_cluster_for_one_sample
from tests.test_regime_pools_helpers import test_offline_regime_cluster_models_limits_cluster_count_to_sample_size
from tests.test_regime_pools_helpers import test_offline_diversification_returns_input_when_already_at_target_count
from tests.test_regime_pools_helpers import test_offline_diversification_selects_unique_models_up_to_target_count
from tests.test_regime_pools_helpers import test_online_model_loader_extract_model_params_excludes_perf_and_metadata_columns
from tests.test_regime_pools_helpers import test_online_model_loader_merge_prediction_dataframes_joins_on_price_keys
from tests.test_regime_pools_helpers import test_aggregation_strategy_supports_mean_median_majority_vote_and_fallback
from tests.test_regime_pools_helpers import test_online_aggregation_run_regime_experiments_skips_failed_models_and_drops_prediction_columns
from tests.test_regime_pools_helpers import test_rdop_offline_pipeline_handles_all_null_metrics_as_single_regime
from tests.test_regime_pools_helpers import test_rdop_online_pipeline_returns_empty_frame_when_no_regime_produces_predictions
from tests.test_regime_pools_helpers import test_rdop_online_pipeline_attaches_prediction_columns_for_each_regime
from tests.test_historical_data import test_get_any_file_loads_local_csv
from tests.test_historical_data import test_get_spot_klines_reaggregates_latest_dataset
from tests.test_historical_data import test_get_spot_klines_rejects_sub_base_intervals
from tests.test_historical_data import test_resolve_file_path_or_url_expands_huggingface_references
from tests.test_historical_data import test_get_any_file_loads_zipped_csv_and_derives_datetime_from_timestamp
from tests.test_historical_data import test_get_any_file_validates_requested_row_count_and_column_names
from tests.test_historical_data import test_get_any_file_rejects_unsupported_extensions
from tests.test_historical_data import test_get_spot_klines_accepts_iso_start_dates_and_rejects_invalid_literals
from tests.test_param_domain import test_param_domain_init
from tests.test_param_domain import test_param_domain_init_validation
from tests.test_param_domain import test_param_domain_defensive_copy
from tests.test_param_domain import test_remove_value
from tests.test_param_domain import test_remove_value_prevents_empty
from tests.test_param_domain import test_remove_values_ge
from tests.test_param_domain import test_remove_values_ge_prevents_empty
from tests.test_param_domain import test_remove_values_le
from tests.test_param_domain import test_keep_values
from tests.test_param_domain import test_keep_values_no_overlap
from tests.test_param_domain import test_keep_between
from tests.test_param_domain import test_inject_value
from tests.test_param_domain import test_observer_notification
from tests.test_param_domain import test_observer_version_increments
from tests.test_param_domain import test_is_valid_combination
from tests.test_param_domain import test_comparison_type_error
from tests.test_param_domain import test_set_state_mismatched_keys
from tests.test_param_domain import test_set_state_observer_rollback
from tests.test_param_domain import test_total_combinations_updates
from tests.test_msq import test_msq_basic_iteration
from tests.test_msq import test_msq_yielded_count
from tests.test_msq import test_priority_queue
from tests.test_msq import test_inject_validates_keys
from tests.test_msq import test_intervention_routing
from tests.test_msq import test_remove_custom
from tests.test_msq import test_filter_exhausted_error
from tests.test_msq import test_trim
from tests.test_msq import test_trim_with_priority_queue
from tests.test_msq import test_remaining_count
from tests.test_msq import test_distribution
from tests.test_msq import test_inject_does_not_mutate_caller_dict
from tests.test_msq import test_n_permutations_stops_iteration
from tests.test_msq import test_mismatched_domain_raises
from tests.test_msq import test_intervention_log
from tests.test_msq import test_set_state_missing_key as test_msq_set_state_missing_key
from tests.test_msq import test_get_set_state
from tests.test_msq import test_set_filter
from tests.test_msq import test_clear_filter
from tests.test_msq import test_set_filter_replaces
from tests.test_msq import test_named_filter_descriptor_roundtrip
from tests.test_msq import test_clear_filter_removes_descriptor
from tests.test_msq import test_non_descriptor_filter_warns_on_restore
from tests.test_pruning_strategy import test_cannot_instantiate_abc
from tests.test_pruning_strategy import test_active_flag
from tests.test_feedback_controller import test_should_trigger_interval
from tests.test_feedback_controller import test_trigger_pruning_strategy
from tests.test_feedback_controller import test_trigger_inactive_pruning_strategy
from tests.test_feedback_controller import test_trigger_intra_callback
from tests.test_feedback_controller import test_apply_intervention_dispatch
from tests.test_feedback_controller import test_apply_intervention_unknown_op
from tests.test_feedback_controller import test_strategy_update_called
from tests.test_feedback_controller import test_trigger_intervention_file
from tests.test_feedback_controller import test_file_polling_skips_unchanged
from tests.test_feedback_controller import test_file_polling_detects_change
from tests.test_feedback_controller import test_file_missing_no_error
from tests.test_feedback_controller import test_file_invalid_json_no_error
from tests.test_feedback_controller import test_source_isolation
from tests.test_feedback_controller import test_pruning_strategy_isolation
from tests.test_feedback_controller import test_audit_log_written
from tests.test_feedback_controller import test_set_state_missing_key as test_fc_set_state_missing_key
from tests.test_feedback_controller import test_get_set_state as test_fc_get_set_state
from tests.test_feedback_controller import test_suggestion_not_dispatched
from tests.test_feedback_controller import test_suggestion_in_audit_log
from tests.test_feedback_controller import test_mixed_interventions_and_suggestions
from tests.test_feedback_controller import test_set_filter_dispatch
from tests.test_feedback_controller import test_clear_filter_dispatch
from tests.test_checkpoint_manager import test_checkpoint_interval_validation
from tests.test_checkpoint_manager import test_should_checkpoint_interval
from tests.test_checkpoint_manager import test_compute_content_hash_dict
from tests.test_checkpoint_manager import test_initialize_fresh_creates_directory
from tests.test_checkpoint_manager import test_save_writes_checkpoint_file
from tests.test_checkpoint_manager import test_save_metadata_content
from tests.test_checkpoint_manager import test_validate_passes_when_all_match
from tests.test_checkpoint_manager import test_validate_raises_on_hash_mismatch
from tests.test_checkpoint_manager import test_validate_raises_on_strategy_mismatch
from tests.test_checkpoint_manager import test_second_checkpoint_overwrites_first
from tests.test_checkpoint_manager import test_load_raises_on_missing_checkpoint
from tests.test_checkpoint_manager import test_load_raises_on_non_dict_checkpoint
from tests.test_checkpoint_manager import test_load_raises_on_corrupt_checkpoint
from tests.test_checkpoint_manager import test_validate_raises_on_missing_checkpoint
from tests.test_checkpoint_manager import test_validate_raises_on_corrupt_checkpoint
from tests.test_checkpoint_manager import test_validate_raises_on_non_dict_checkpoint
from tests.test_checkpoint_manager import test_validate_raises_on_missing_metadata_key
from tests.test_checkpoint_manager import test_validate_raises_on_invalid_metadata_type
from tests.test_checkpoint_manager import test_validate_raises_on_missing_experiment_round
from tests.test_checkpoint_manager import test_validate_raises_on_missing_target_permutations
from tests.test_checkpoint_manager import test_validate_raises_on_missing_msq_state
from tests.test_checkpoint_manager import test_validate_raises_on_missing_domain_state
from tests.test_checkpoint_manager import test_validate_raises_on_invalid_msq_state_type
from tests.test_checkpoint_manager import test_validate_raises_on_invalid_domain_state_type
from tests.test_checkpoint_manager import test_param_domain_set_state_invalid_leaves_state_unchanged
from tests.test_checkpoint_manager import test_param_domain_get_set_state
from tests.test_checkpoint_manager import test_uel_shutdown_flag
from tests.test_checkpoint_manager import test_uel_double_signal_raises
from tests.test_checkpoint_manager import test_uel_checkpoint_and_resume
from tests.test_experiment_core_msq import test_run_with_msq_basic_flow
from tests.test_experiment_core_msq import test_run_with_msq_context_params
from tests.test_experiment_core_msq import test_run_with_msq_feedback_trigger
from tests.test_experiment_core_msq import test_run_with_msq_checkpoint_trigger
from tests.test_splits import test_prep_output_ml_path
from tests.test_splits import test_rule_based_prep_output_returns_full_dataframes
from tests.test_rule_based_metrics import test_num_trades_counts_entries_not_bars
from tests.test_rule_based_metrics import test_position_rate
from tests.test_rule_based_metrics import test_backtest_metrics_flattened_with_split_suffix
from tests.test_rule_based_metrics import test_sharpe_std_and_drawdown_std
from tests.test_rule_based_metrics import test_sharpe_degradation
from tests.test_rule_based_metrics import test_is_stable_true_when_within_thresholds
from tests.test_rule_based_metrics import test_is_stable_false_when_sharpe_std_exceeds_threshold
from tests.test_rule_based_metrics import test_missing_backtest_results_degrade_gracefully
from tests.test_manifest_rule_based import test_with_strategy_sets_sentinel_and_returns_self
from tests.test_manifest_rule_based import test_prepare_data_rule_based_returns_split_dataframes
from tests.test_manifest_rule_based import test_prepare_data_rule_based_adds_predicate_columns
from tests.test_manifest_rule_based import test_prepare_data_rule_based_attaches_strategy_config
from tests.test_manifest_rule_based import test_prepare_data_rule_based_compound_condition_not_added_as_column
from tests.test_manifest_rule_based import test_prepare_data_rule_based_rejects_scaler
from tests.test_manifest_rule_based import test_prepare_data_rule_based_rejects_ablation
from tests.test_manifest_rule_based import test_prepare_data_rule_based_rejects_condition_id_colliding_with_column
from tests.test_predicates import test_threshold
from tests.test_predicates import test_relative
from tests.test_predicates import test_crossover_above
from tests.test_predicates import test_crossover_below
from tests.test_predicates import test_slope_rising
from tests.test_predicates import test_slope_falling
from tests.test_predicates import test_with_persistence
from tests.test_predicates import test_with_recency
from tests.test_predicates import test_sql_expr_escape_hatch
from tests.test_predicates import test_build_predicate_threshold_with_param_substitution
from tests.test_predicates import test_build_predicate_unknown_type_raises
from tests.test_predicates import test_threshold_unknown_operator_raises
from tests.test_predicates import test_sql_expr_missing_param_raises
from tests.test_predicates import test_rule_based_config_cycle_detection
from tests.test_predicates import test_rule_based_config_operands_must_be_list
from tests.test_predicates import test_rule_based_config_operand_elements_must_be_strings
from tests.test_experiment_core_standard_csv import test_standard_run_csv_round_trips_special_string_fields
from tests.test_experiment_core_standard_csv import test_standard_run_csv_does_not_append_duplicate_headers_on_rerun
from tests.test_experiment_core_standard_csv import test_standard_run_csv_uses_experiment_dir
from tests.test_experiment_core_standard_csv import test_standard_run_rechunks_live_log_without_changing_row_output
from tests.test_runtime_tracking import test_execute_test_suite_writes_profile_and_stops_on_first_failure
from tests.test_runtime_tracking import test_runtime_gate_writes_summary_and_passes_when_within_budget
from tests.test_runtime_tracking import test_runtime_gate_fails_when_profile_exceeds_budget
from tests.test_experiment_core_msq import test_checkpoint_saves_feedback_and_pruning_state
from tests.test_experiment_core_msq import test_run_with_msq_shutdown_resume_full_data
from tests.test_experiment_core_msq import test_run_with_msq_shutdown_resume_grid
from tests.test_experiment_core_msq import test_shutdown_before_any_round_completes
from tests.test_experiment_core_msq import test_resume_fails_without_round_data
from tests.test_experiment_core_msq import test_preds_none_does_not_crash
from tests.test_experiment_core_msq import test_resume_truncates_stale_rounds
from tests.test_experiment_core_msq import test_truncate_round_data_unit
from tests.test_experiment_core_msq import test_experiment_parameter_correlation_keeps_numeric_signal_columns_and_orders_cohorts
from tests.test_experiment_core_msq import test_experiment_parameter_correlation_validates_metric_and_sort_key_presence
from tests.test_experiment_core_msq import test_experiment_parameter_correlation_requires_numeric_features_after_cleaning
from tests.test_experiment_core_msq import test_experiment_parameter_correlation_rejects_logs_without_metric_rows
from tests.test_experiment_core_msq import test_uel_test_mode_routes_to_test_data_source
from tests.test_sanity_reducer import test_nan_above_threshold
from tests.test_sanity_reducer import test_min_observations_gate
from tests.test_sanity_reducer import test_early_returns
from tests.test_sanity_reducer import test_multiple_params_pruned
from tests.test_sanity_reducer import test_dedup_across_triggers
from tests.test_sanity_reducer import test_boundary_exact_threshold
from tests.test_sanity_reducer import test_zero_metric_suggestion
from tests.test_sanity_reducer import test_zero_metric_disabled_by_default
from tests.test_sanity_reducer import test_execution_timeout_suggestion
from tests.test_sanity_reducer import test_warning_suggestion
from tests.test_sanity_reducer import test_warning_no_column
from tests.test_sanity_reducer import test_suggestion_dedup
from tests.test_sanity_reducer import test_suggestion_checkpoint_roundtrip
from tests.test_indicators_vs_talib import test_indicators_vs_talib
from tests.test_correlation_reducer import test_wrong_direction_removal
from tests.test_correlation_reducer import test_low_impact_suggestion
from tests.test_correlation_reducer import test_dedup_across_triggers as test_corr_dedup_across_triggers
from tests.test_correlation_reducer import test_early_returns as test_corr_early_returns
from tests.test_correlation_reducer import test_insufficient_data_for_correlation
from tests.test_correlation_reducer import test_state_roundtrip as test_corr_state_roundtrip
from tests.test_correlation_reducer import test_set_state_missing_key as test_corr_set_state_missing_key
from tests.test_correlation_reducer import test_maximize_false
from tests.test_correlation_reducer import test_sign_stability_below_threshold
from tests.test_saturation_reducer import test_saturated_value_filter
from tests.test_saturation_reducer import test_no_saturation
from tests.test_saturation_reducer import test_early_returns as test_sat_early_returns
from tests.test_saturation_reducer import test_window_size
from tests.test_saturation_reducer import test_zero_mean_skipped
from tests.test_saturation_reducer import test_unsaturation_clears_filter
from tests.test_saturation_reducer import test_state_roundtrip as test_sat_state_roundtrip
from tests.test_saturation_reducer import test_set_state_missing_key as test_sat_set_state_missing_key
from tests.test_saturation_reducer import test_constructor_validation as test_sat_constructor_validation
from tests.test_focus_reducer import test_breakthrough_activates_focus
from tests.test_focus_reducer import test_no_breakthrough
from tests.test_focus_reducer import test_maximize_false as test_focus_maximize_false
from tests.test_focus_reducer import test_early_returns as test_focus_early_returns
from tests.test_focus_reducer import test_snap_back_after_timeout
from tests.test_focus_reducer import test_improvement_resets_timeout
from tests.test_focus_reducer import test_numeric_narrowing_range
from tests.test_focus_reducer import test_categorical_narrowing
from tests.test_focus_reducer import test_zero_center_narrowing
from tests.test_focus_reducer import test_variation_injection_count
from tests.test_focus_reducer import test_variation_injection_linspace
from tests.test_focus_reducer import test_no_injection_on_improvement
from tests.test_focus_reducer import test_mixed_param_types as test_focus_mixed_param_types
from tests.test_focus_reducer import test_improvement_updates_combo
from tests.test_focus_reducer import test_state_roundtrip as test_focus_state_roundtrip
from tests.test_focus_reducer import test_set_state_missing_key as test_focus_set_state_missing_key
from tests.test_budget_reducer import test_constructor_validation as test_budget_constructor_validation
from tests.test_budget_reducer import test_early_returns as test_budget_early_returns
from tests.test_budget_reducer import test_trimmed_flag_prevents_retrim
from tests.test_budget_reducer import test_permutation_budget_trim_random
from tests.test_budget_reducer import test_permutation_budget_check_after_pct_gate
from tests.test_budget_reducer import test_walltime_budget_trim
from tests.test_budget_reducer import test_walltime_exceeded
from tests.test_budget_reducer import test_no_trim_when_within_budget
from tests.test_budget_reducer import test_worst_first_trim
from tests.test_budget_reducer import test_worst_first_fallback_to_random
from tests.test_budget_reducer import test_remaining_none_with_permutation_budget
from tests.test_budget_reducer import test_walltime_zero_elapsed
from tests.test_budget_reducer import test_worst_first_includes_trim_fallback
from tests.test_budget_reducer import test_both_budgets_takes_min
from tests.test_budget_reducer import test_no_budget_configured
from tests.test_budget_reducer import test_state_roundtrip as test_budget_state_roundtrip
from tests.test_budget_reducer import test_set_state_missing_key as test_budget_set_state_missing_key
from tests.test_budget_reducer import test_worst_first_maximize_false
from tests.test_reference_architecture import test_xgboost_train_returns_fitted_model
from tests.test_reference_architecture import test_xgboost_evaluate_returns_all_metric_types
from tests.test_reference_architecture import test_logreg_train_evaluate_end_to_end
from tests.test_reference_architecture import test_random_binary_train_evaluate_end_to_end
from tests.test_reference_architecture import test_tabpfn_train_evaluate_end_to_end
from tests.test_reference_architecture import test_train_with_validation_data
from tests.test_reference_architecture import test_train_without_validation_data
from tests.test_reference_architecture import test_rule_based_train_is_noop
from tests.test_reference_architecture import test_rule_based_evaluate_returns_expected_metrics
from tests.test_reference_architecture import test_rule_based_is_stable_respects_thresholds
from tests.test_reference_architecture import test_rule_based_function_returns_flat_dict
from tests.test_reference_architecture import test_rule_based_or_compound_condition
from tests.test_reference_architecture import test_rule_based_not_operator
from tests.test_reference_architecture import test_rule_based_empty_operands_raises
from tests.test_reference_architecture import test_rule_based_unknown_operator_raises
from tests.test_manifest_prepare_data import test_price_data_for_backtest_has_ohlc_columns
from tests.test_manifest_prepare_data import test_price_data_for_backtest_row_count_matches_test
from tests.test_manifest_prepare_data import test_price_data_for_backtest_datetime_alignment
from tests.test_manifest_prepare_data import test_shifted_target_pipeline_keeps_price_rows_on_feature_bar
from tests.test_manifest_prepare_data import test_logreg_manifest_keeps_price_rows_on_the_feature_bar
from tests.test_manifest_prepare_data import test_override_split_config
from tests.test_manifest_prepare_data import test_override_data_source_param
from tests.test_manifest_prepare_data import test_override_multiple_params
from tests.test_manifest_prepare_data import test_override_param_not_in_original_but_in_signature
from tests.test_manifest_prepare_data import test_unknown_override_key_raises
from tests.test_inline_metrics import test_inline_and_post_experiment_metrics
from tests.test_inline_metrics import test_logreg_inline_and_post_confusion_metrics_match
from tests.test_inline_metrics import test_xgboost_inline_and_post_backtest_metrics_match
from tests.test_metrics_and_log_helpers import test_backtest_snapshot_executes_on_next_bar
from tests.test_metrics_and_log_helpers import test_backtest_snapshot_preserves_shifted_hold_while_one_continuation
from tests.test_metrics_and_log_helpers import test_backtest_snapshot_applies_costs_multiplicatively_per_fill
from tests.test_metrics_and_log_helpers import test_backtest_snapshot_drawdown_includes_starting_equity_peak
from tests.test_metrics_and_log_helpers import test_backtest_snapshot_drops_predictions_without_immediate_next_execution_bar
from tests.test_metrics_and_log_helpers import test_completed_bar_signal_proves_next_bar_alignment
from tests.test_metrics_and_log_helpers import test_backtest_snapshot_rejects_empty_input
from tests.test_metrics_and_log_helpers import test_backtest_snapshot_rejects_inconsistent_price_change
from tests.test_metrics_and_log_helpers import test_backtest_snapshot_rejects_missing_predictions
from tests.test_metrics_and_log_helpers import test_backtest_snapshot_rejects_non_binary_predictions
from tests.test_metrics_and_log_helpers import test_backtest_snapshot_rejects_non_numeric_price_values
from tests.test_metrics_and_log_helpers import test_experiment_backtest_results_directionalizes_regression_predictions
from tests.test_metrics_and_log_helpers import test_permutation_confusion_metrics_adds_mean_return_pct_columns
from tests.test_metrics_and_log_helpers import test_permutation_confusion_metrics_keeps_mean_returns_on_unfiltered_rows
from tests.test_metrics_and_log_helpers import test_permutation_confusion_metrics_uses_positional_alignment_for_returns
from tests.test_metrics_and_log_helpers import test_permutation_confusion_metrics_requires_return_columns
from tests.test_metrics_and_log_helpers import test_prepare_snapshot_backtest_input_rejects_multiclass
from tests.test_metrics_and_log_helpers import test_prepare_snapshot_backtest_input_rejects_non_numeric_logged_values
from tests.test_log_read_from_file import test_read_from_file_matches_full_header_and_keeps_non_header_recall_rows
from tests.test_log_read_from_file import test_read_from_file_removes_duplicate_headers_and_trims_object_columns
from tests.test_feature_library_primitives import test_atr_sma_matches_manual_true_range_average
from tests.test_feature_library_primitives import test_atr_percent_sma_scales_atr_by_close
from tests.test_feature_library_primitives import test_close_position_uses_intra_candle_range
from tests.test_feature_library_primitives import test_distance_features_use_rolling_highs_and_lows
from tests.test_feature_library_primitives import test_gap_high_uses_previous_close
from tests.test_feature_library_primitives import test_price_range_position_tracks_close_within_rolling_channel
from tests.test_feature_library_primitives import test_trend_strength_uses_fast_and_slow_moving_average_divergence
from tests.test_feature_library_primitives import test_volume_ratio_builds_missing_baseline_sma
from tests.test_feature_library_primitives import test_volume_ratio_respects_existing_baseline_column
from tests.test_feature_library_primitives import test_volume_regime_compares_recent_volume_to_longer_average
from tests.test_feature_library_primitives import test_ichimoku_cloud_builds_shifted_components
from tests.test_feature_library_primitives import test_sma_crossover_marks_bullish_and_bearish_crosses
from tests.test_feature_library_regimes import test_close_to_extremes_reports_relative_distance_to_high_and_low
from tests.test_feature_library_regimes import test_dynamic_stop_loss_clips_volatility_adjusted_levels
from tests.test_feature_library_regimes import test_dynamic_target_clips_volatility_adjusted_targets
from tests.test_feature_library_regimes import test_exit_quality_distinguishes_good_bad_and_neutral_exits
from tests.test_feature_library_regimes import test_log_returns_uses_log_ratio_of_consecutive_prices
from tests.test_feature_library_regimes import test_micro_momentum_uses_period_pct_change
from tests.test_feature_library_regimes import test_momentum_weight_only_boosts_positive_momentum
from tests.test_feature_library_regimes import test_position_in_range_matches_candle_fraction_formula
from tests.test_feature_library_regimes import test_regime_multiplier_maps_low_normal_and_high_regimes
from tests.test_feature_library_regimes import test_spread_and_spread_percent_match_same_ratio
from tests.test_feature_library_regimes import test_calendar_time_features_extract_discrete_fields
from tests.test_feature_library_regimes import test_cyclical_time_features_extract_sine_and_cosine_fields
from tests.test_feature_library_regimes import test_volatility_1h_copies_requested_source_column
from tests.test_feature_library_regimes import test_volatility_measure_averages_rolling_volatility_and_atr_percent
from tests.test_feature_library_regimes import test_ema_alignment_adds_ema_and_alignment_score
from tests.test_feature_library_regimes import test_position_in_candle_matches_range_fraction
from tests.test_feature_library_regimes import test_risk_reward_ratio_uses_absolute_drawdown_with_epsilon_guard
from tests.test_feature_library_regimes import test_volume_spike_supports_ratio_and_zscore_modes
from tests.test_feature_library_regimes import test_breakout_percentile_regime_labels_up_flat_and_down
from tests.test_feature_library_regimes import test_window_return_regime_labels_positive_negative_and_neutral_windows
from tests.test_feature_library_range_volatility import test_range_based_volatility_estimators_match_constant_ratio_bars
from tests.test_feature_library_range_volatility import test_yang_zhang_volatility_handles_zero_overnight_jumps_and_rejects_tiny_windows
from tests.test_feature_library_liquidity import test_liquidity_features_match_manual_ohlcv_impact_formulas
from tests.test_feature_library_liquidity import test_return_per_dollar_volume_and_amihud_handle_zero_dollar_volume_with_epsilon_guard
from tests.test_feature_library_realized_risk import test_realized_semivariance_separates_upside_and_downside_return_energy
from tests.test_feature_library_realized_risk import test_realized_skewness_and_kurtosis_match_manual_standardized_moments
from tests.test_feature_library_realized_risk import test_jump_variation_proxy_matches_manual_realized_minus_bipower_component
from tests.test_feature_library_realized_risk import test_jump_variation_proxy_returns_null_when_window_cannot_form_bipower_pairs
from tests.test_feature_library_realized_risk import test_tail_event_intensity_lights_up_after_repeated_large_shocks
from tests.test_feature_library_realized_risk import test_volatility_of_volatility_matches_nested_sample_standard_deviation
from tests.test_feature_library_seasonality import test_relative_volume_and_range_seasonality_compare_against_same_hour_of_week_history
from tests.test_feature_library_seasonality import test_relative_volatility_seasonality_uses_same_hour_of_week_absolute_returns
from tests.test_feature_library_candle_structure import test_candle_structure_features_capture_body_wicks_overlap_and_rejection
from tests.test_feature_library_cross_timescale import test_trend_coherence_scores_full_and_partial_directional_agreement
from tests.test_feature_library_cross_timescale import test_volatility_term_structure_matches_manual_front_vs_back_ratio_average
from tests.test_feature_library_composites import test_feature_aliases_fill_nulls_and_build_regime_aliases
from tests.test_feature_library_composites import test_feature_aliases_can_skip_regime_aliases
from tests.test_feature_library_composites import test_returns_lags_builds_returns_when_missing
from tests.test_feature_library_composites import test_returns_lags_respects_existing_returns_column
from tests.test_feature_library_composites import test_volume_weight_uses_clipped_ratio_to_volume_average
from tests.test_feature_library_composites import test_momentum_confirmation_combines_short_and_long_signals
from tests.test_feature_library_composites import test_momentum_confirmation_rejects_invalid_period_order
from tests.test_feature_library_composites import test_volatility_weight_inversely_scales_rolling_volatility
from tests.test_feature_library_composites import test_momentum_periods_adds_requested_period_columns
from tests.test_feature_library_composites import test_volume_trend_compares_short_and_long_volume_averages
from tests.test_feature_library_composites import test_entry_score_microstructure_switches_weights_by_regime
from tests.test_feature_library_composites import test_ema_breakout_labels_future_moves_above_ema_threshold
from tests.test_feature_library_composites import test_hh_hl_structure_regime_detects_up_flat_and_down_windows
from tests.test_feature_library_composites import test_ma_slope_regime_uses_sma_slope_direction
from tests.test_feature_library_composites import test_price_vs_band_regime_flags_prices_outside_rolling_bands
from tests.test_feature_library_context import test_active_lines_counts_overlapping_long_and_short_spans
from tests.test_feature_library_context import test_active_lines_returns_zero_when_no_lines_or_rows_exist
from tests.test_feature_library_context import test_active_quantile_count_tracks_quantile_filtered_spans
from tests.test_feature_library_context import test_quantile_line_density_counts_recent_line_endings_within_lookback
from tests.test_feature_library_context import test_market_regime_keeps_parameterized_smas_and_adds_normalized_aliases
from tests.test_indicator_and_data_helpers import test_ema_segment_returns_empty_when_requested_range_is_before_lookback
from tests.test_indicator_and_data_helpers import test_ema_segment_matches_manual_recursive_values
from tests.test_indicator_and_data_helpers import test_default_ema_segment_uses_standard_talib_constant
from tests.test_indicator_and_data_helpers import test_stddev_from_var_matches_manual_rolling_std_and_returns_empty_before_lookback
from tests.test_indicator_and_data_helpers import test_stddev_using_precalc_ma_matches_manual_window_std
from tests.test_indicator_and_data_helpers import test_ht_phasor_short_inputs_return_nan_only_and_wrapper_uses_custom_price_col
from tests.test_indicator_and_data_helpers import test_ht_phasor_constant_signal_stays_zero_after_lookback_and_matches_wrapper
from tests.test_indicator_and_data_helpers import test_ht_phasor_oscillating_signal_produces_distinct_components
from tests.test_indicator_and_data_helpers import test_ht_sine_short_inputs_return_nan_only_and_wrapper_outputs_bounded_values
from tests.test_indicator_and_data_helpers import test_ht_sine_constant_signal_converges_to_stable_bounded_outputs
from tests.test_indicator_and_data_helpers import test_ht_sine_oscillating_signal_matches_wrapper_and_has_phase_advanced_lead
from tests.test_indicator_and_data_helpers import test_price_change_pct_computes_percentage_change_from_prior_close
from tests.test_indicator_and_data_helpers import test_returns_matches_polars_pct_change_convention
from tests.test_indicator_and_data_helpers import test_rsi_sma_is_neutral_when_recent_gains_and_losses_balance
from tests.test_indicator_and_data_helpers import test_random_slice_rejects_invalid_safe_range_bounds
from tests.test_indicator_and_data_helpers import test_random_slice_rejects_slice_that_cannot_fit_safe_range
from tests.test_indicator_and_data_helpers import test_random_slice_returns_contiguous_window_inside_safe_range
from tests.test_indicator_and_data_helpers import test_split_sequential_preserves_order_and_uses_all_rows
from tests.test_indicator_and_data_helpers import test_split_random_creates_reproducible_partition_with_full_coverage
from tests.test_indicator_and_data_helpers import test_split_data_to_prep_output_builds_expected_alignment_metadata
from tests.test_indicator_and_data_helpers import test_split_data_to_prep_output_requires_datetime_column
from tests.test_indicator_and_data_helpers import test_data_dict_to_numpy_converts_requested_polars_entries
from tests.test_indicator_and_data_helpers import test_data_dict_to_numpy_respects_custom_keys_and_preserves_numpy_values
from tests.test_metrics_and_log_helpers import test_permutation_prediction_performance_preserves_inverse_scaled_features
from tests.test_metrics_and_log_helpers import test_permutation_prediction_performance_falls_back_to_single_argument_prep
from tests.test_metrics_and_log_helpers import test_multiclass_metrics_returns_expected_rounded_summary
from tests.test_metrics_and_log_helpers import test_balanced_metric_returns_zero_without_positive_predictions
from tests.test_metrics_and_log_helpers import test_balanced_metric_penalizes_sparse_precision_by_trade_rate
from tests.test_metrics_and_log_helpers import test_reporting_helpers_honor_requested_width_and_titles
from tests.test_transforms import test_mad_transform_scales_around_column_median_and_preserves_context_columns
from tests.test_transforms import test_zscore_transform_centers_numeric_values_and_guards_constant_columns
from tests.test_transforms import test_winsorize_transform_clips_extreme_tail_values
from tests.test_transforms import test_quantile_trim_transform_removes_tail_rows_and_preserves_nulls
from tests.test_transforms import test_numeric_transforms_leave_non_numeric_frames_unchanged
from tests.test_calibration import test_sklearn_probability_calibrator_no_future_warning
from tests.test_calibration import test_grid_threshold_optimizer_picks_best_balanced_threshold
from tests.test_calibration import test_grid_threshold_optimizer_returns_default_when_all_thresholds_predict_zero
from tests.test_calibration import test_grid_threshold_optimizer_returns_bounded_threshold
from tests.test_calibration import test_calibration_config_resolve_substitutes_string_params
from tests.test_calibration import test_calibration_builder_done_raises_without_any_func
from tests.test_calibration import test_run_model_injects_resolved_prediction_calibration_config
from tests.test_calibration import test_run_model_no_injection_when_calibration_not_set
from tests.test_calibration import test_run_model_no_injection_when_both_flags_false
from tests.test_calibration import test_run_model_masks_calibration_func_when_use_calibration_false
from tests.test_calibration import test_run_model_masks_threshold_func_when_use_threshold_false
from tests.test_calibration import test_logreg_predict_without_calibration_unchanged
from tests.test_calibration import test_logreg_predict_threshold_only_returns_threshold_keys
from tests.test_feature_perturbation import test_add_indicator_creates_transform_entry
from tests.test_feature_perturbation import test_feature_group_filtering_includes_selected
from tests.test_feature_perturbation import test_feature_group_filtering_multiple_groups
from tests.test_feature_perturbation import test_feature_group_absent_includes_all
from tests.test_feature_perturbation import test_combined_group_and_include_if
from tests.test_feature_perturbation import test_include_if_true
from tests.test_feature_perturbation import test_include_if_false
from tests.test_feature_perturbation import test_include_if_key_missing_includes
from tests.test_feature_perturbation import test_ablation_drops_correct_count
from tests.test_feature_perturbation import test_ablation_deterministic_with_seed
from tests.test_feature_perturbation import test_ablation_zero_drops_nothing
from tests.test_feature_perturbation import test_ablation_preserves_datetime_and_target
from tests.test_feature_perturbation import test_ablation_consistent_across_splits
from tests.test_feature_perturbation import test_ungrouped_features_always_included
from tests.test_feature_perturbation import test_ablation_not_configured_noop
from tests.test_feature_perturbation import test_feature_groups_all_includes_everything
from tests.test_feature_perturbation import test_ablation_invalid_drop_count_raises
from tests.test_scalers import test_robust_scaler_fit_and_transform
from tests.test_scalers import test_robust_scaler_custom_quantile_range
from tests.test_scalers import test_robust_scaler_zero_iqr_guard
from tests.test_scalers import test_robust_scaler_preserves_datetime
from tests.test_scalers import test_robust_scaler_outlier_resilience
from tests.test_scalers import test_rank_gauss_output_approximately_normal
from tests.test_scalers import test_rank_gauss_preserves_rank_order
from tests.test_scalers import test_rank_gauss_handles_unseen_values
from tests.test_scalers import test_rank_gauss_preserves_datetime
from tests.test_scalers import test_rank_gauss_constant_column
from tests.test_scalers import test_rank_gauss_integer_column
from tests.test_scalers import test_robust_scaler_inverse_transform
from tests.test_scalers import test_rank_gauss_inverse_transform
from tests.test_scalers import test_robust_scaler_invalid_quantile_range
from tests.test_scalers import test_rank_gauss_invalid_n_quantiles
from tests.test_scalers import test_robust_scaler_all_null_column
from tests.test_scalers import test_scaler_factory_selects_all_types
from tests.test_scalers import test_scaler_factory_unknown_raises
from tests.test_scalers import test_scaler_factory_registry_has_all
from tests.test_targets import test_quantile_binary_fits_cutoff_on_train
from tests.test_targets import test_quantile_binary_transform_labels_above_cutoff
from tests.test_targets import test_quantile_binary_shift_applied_when_nonzero
from tests.test_targets import test_forward_breakout_labels_above_threshold
from tests.test_targets import test_forward_breakout_shift_applied
from tests.test_targets import test_threshold_binary_labels_above_threshold
from tests.test_targets import test_threshold_binary_threshold_is_fixed
from tests.test_targets import test_threshold_binary_shift_applied
from tests.test_targets import test_next_return_computes_percentage_return
from tests.test_targets import test_next_return_respects_periods
from tests.test_targets import test_next_return_respects_scale
from tests.test_targets import test_with_target_label_sets_target_class_config
from tests.test_targets import test_with_target_label_applies_transform_to_all_splits
from tests.test_targets import test_with_target_label_fits_only_on_train
from tests.test_targets import test_random_binary_target_adds_column_with_binary_values
from tests.test_targets import test_identity_target_returns_data_unchanged
from tests.test_targets import test_identity_target_raises_when_column_missing_on_init
from tests.test_targets import test_identity_target_raises_when_column_missing_on_transform
from tests.test_feature_perturbation import test_ablation_drop_count_exceeds_eligible_raises
from tests.test_reducer_factory import test_reducer_registry_has_all_types
from tests.test_reducer_factory import test_reducer_registry_maps_to_correct_classes
from tests.test_reducer_factory import test_reducer_registry_unknown_key_raises
from tests.test_search_strategies import test_random_basic_iteration
from tests.test_search_strategies import test_random_seeded_reproducibility
from tests.test_search_strategies import test_random_dedup_skips_seen
from tests.test_search_strategies import test_random_get_set_state
from tests.test_search_strategies import test_random_rebuild_seen_from_log
from tests.test_search_strategies import test_random_with_msq
from tests.test_search_strategies import test_injected_combo_registered_in_seen
from tests.test_search_strategies import test_random_on_domain_changed
from tests.test_search_strategies import test_random_large_domain
from tests.test_search_strategies import test_grid_exhaustive_small_space
from tests.test_search_strategies import test_grid_covers_full_space
from tests.test_search_strategies import test_grid_deterministic_order
from tests.test_search_strategies import test_grid_shuffle_covers_full_space
from tests.test_search_strategies import test_grid_shuffle_different_order
from tests.test_search_strategies import test_grid_shuffle_seeded_reproducibility
from tests.test_search_strategies import test_grid_get_set_state
from tests.test_search_strategies import test_grid_on_domain_changed
from tests.test_search_strategies import test_grid_large_space_shuffle
from tests.test_search_strategies import test_grid_with_msq
from tests.test_search_strategies import test_strategy_registry
from tests.test_search_strategies import test_param_hash_deterministic
from tests.test_search_strategies import test_param_hash_key_order_independent
from tests.test_search_strategies import test_param_hash_different_combos_differ
from tests.test_fractional_diff import test_fractional_diff_d_zero_copies
from tests.test_fractional_diff import test_fractional_diff_d_one_equals_first_diff
from tests.test_fractional_diff import test_fractional_diff_weights_convergence
from tests.test_fractional_diff import test_fractional_diff_preserves_original_columns
from tests.test_fractional_diff import test_fractional_diff_cols_none_raises
from tests.test_fractional_diff import test_fractional_diff_negative_d_raises
from tests.test_fractional_diff import test_fractional_diff_lazyframe
from tests.test_fractional_diff import test_adf_test_stationary_series
from tests.test_fractional_diff import test_adf_test_nonstationary_series
from tests.test_fractional_diff import test_find_min_d_returns_valid_d
from tests.test_fractional_diff import test_fractional_diff_empty_dataframe
from tests.test_fractional_diff import test_fractional_diff_missing_column_skips
from tests.test_fractional_diff import test_adf_test_empty_series
from tests.test_fractional_diff import test_adf_test_constant_series
from tests.test_fractional_diff import test_find_min_d_step_zero_raises
from tests.test_fractional_diff import test_find_min_d_small_data_skips
from tests.test_manifest_prepare_data import test_split_validation_rejects_invalid
from tests.test_manifest_prepare_data import test_column_consistency_drops_mismatched_columns
from tests.test_fractional_diff import test_fractional_diff_manifest_integration
from tests.test_trainer import test_trainer_end_to_end
from tests.test_trainer import test_reconstruction_error_stochastic
from tests.test_trainer import test_reconstruction_error_tampered_log
from tests.test_trainer import test_deterministic_validation
from tests.test_trainer import test_pass2_uses_full_data
from tests.test_trainer import test_sensor_inference
from tests.test_trainer import test_trainer_with_feature_ablation
from tests.test_trainer import test_trainer_with_fractional_diff
from tests.test_trainer import test_load_round_data_skips_blank_and_malformed_lines
from tests.test_trainer import test_load_round_data_requires_round_data_file
from tests.test_trainer import test_load_original_log_returns_none_when_results_csv_is_missing
from tests.test_trainer import test_resolve_model_class_requires_configured_architecture_function
from tests.test_trainer import test_resolve_model_class_rejects_modules_without_reference_model_subclasses
from tests.test_trainer import test_resolve_model_class_rejects_modules_with_multiple_reference_model_subclasses
from tests.test_trainer import test_validate_metrics_ignores_metadata_fields_and_accepts_small_stochastic_drift
from tests.test_trainer import test_validate_metrics_reports_missing_permutations_and_large_deterministic_mismatches
from tests.test_proto_cohort import test_rejects_when_no_source_provided
from tests.test_proto_cohort import test_rejects_when_both_sources_provided
from tests.test_proto_cohort import test_rejects_missing_experiment_log_path
from tests.test_proto_cohort import test_defaults_to_all_permutations_when_not_provided
from tests.test_proto_cohort import test_rejects_empty_permutation_ids
from tests.test_proto_cohort import test_rejects_duplicate_permutation_ids
from tests.test_proto_cohort import test_rejects_unknown_permutation_ids
from tests.test_proto_cohort import test_accepts_string_permutation_ids_when_numeric
from tests.test_proto_cohort import test_rejects_when_round_data_is_missing
from tests.test_proto_cohort import test_rejects_unresolvable_experiment_id
from tests.test_proto_cohort import test_rejects_ambiguous_experiment_id_resolution
from tests.test_proto_cohort import test_rejects_mixed_architecture_selection
from tests.test_proto_cohort import test_sets_probability_mode_for_probability_capable_architecture
from tests.test_proto_cohort import test_sets_fallback_mode_for_non_probability_architecture
from tests.test_proto_cohort import test_probability_weighted_predict_aggregates_mean_p1
from tests.test_proto_cohort import test_probability_weighted_predict_single_member_matches_own_thresholded_probs
from tests.test_proto_cohort import test_single_decoder_passthrough_returns_member_preds_unchanged
from tests.test_proto_cohort import test_probability_weighted_predict_requires_members
from tests.test_proto_cohort import test_majority_vote_tie_returns_zero
from tests.test_proto_cohort import test_probability_weighted_tie_returns_zero
from tests.test_proto_cohort import test_majority_vote_multimember_expected_output
from tests.test_proto_cohort import test_probability_weighted_vote_rejects_shape_mismatch
from tests.test_proto_cohort import test_majority_vote_rejects_shape_mismatch
from tests.test_proto_cohort import test_predict_return_meta_returns_metadata_placeholder
from tests.test_proto_cohort import test_predict_return_probs_and_return_meta_returns_three_tuple
from tests.test_proto_cohort import test_predict_return_probs_rejected_in_fallback_mode
from tests.test_proto_cohort import test_validate_probability_range_accepts_values_in_unit_interval
from tests.test_proto_cohort import test_validate_probability_range_rejects_out_of_range_values
from tests.test_proto_cohort import test_validate_probability_range_rejects_non_finite_values
from tests.test_proto_cohort import test_cohort_is_drop_in_decoder_replacement_for_dict_input
from tests.test_proto_cohort import test_member_failure_propagates_and_fails_whole_call
from tests.test_proto_cohort import test_predict_return_probs_probability_mode_returns_per_sample_probs
from tests.test_proto_cohort import test_predict_return_probs_single_member_returns_sample_major_column
from tests.test_proto_cohort import test_majority_vote_uses_binary_votes_for_continuous_fallback_members
from tests.test_proto_cohort import test_single_member_fallback_predict_returns_binary_votes

tests = [
    test_param_domain_init,
    test_param_domain_init_validation,
    test_param_domain_defensive_copy,
    test_remove_value,
    test_remove_value_prevents_empty,
    test_remove_values_ge,
    test_remove_values_ge_prevents_empty,
    test_remove_values_le,
    test_keep_values,
    test_keep_values_no_overlap,
    test_keep_between,
    test_inject_value,
    test_observer_notification,
    test_observer_version_increments,
    test_is_valid_combination,
    test_comparison_type_error,
    test_set_state_mismatched_keys,
    test_set_state_observer_rollback,
    test_total_combinations_updates,
    test_msq_basic_iteration,
    test_msq_yielded_count,
    test_priority_queue,
    test_inject_validates_keys,
    test_intervention_routing,
    test_remove_custom,
    test_filter_exhausted_error,
    test_trim,
    test_trim_with_priority_queue,
    test_remaining_count,
    test_distribution,
    test_inject_does_not_mutate_caller_dict,
    test_n_permutations_stops_iteration,
    test_mismatched_domain_raises,
    test_intervention_log,
    test_msq_set_state_missing_key,
    test_get_set_state,
    test_set_filter,
    test_clear_filter,
    test_set_filter_replaces,
    test_named_filter_descriptor_roundtrip,
    test_clear_filter_removes_descriptor,
    test_non_descriptor_filter_warns_on_restore,
    test_cannot_instantiate_abc,
    test_active_flag,
    test_should_trigger_interval,
    test_trigger_pruning_strategy,
    test_trigger_inactive_pruning_strategy,
    test_trigger_intra_callback,
    test_apply_intervention_dispatch,
    test_apply_intervention_unknown_op,
    test_strategy_update_called,
    test_trigger_intervention_file,
    test_file_polling_skips_unchanged,
    test_file_polling_detects_change,
    test_file_missing_no_error,
    test_file_invalid_json_no_error,
    test_source_isolation,
    test_pruning_strategy_isolation,
    test_audit_log_written,
    test_fc_set_state_missing_key,
    test_fc_get_set_state,
    test_suggestion_not_dispatched,
    test_suggestion_in_audit_log,
    test_mixed_interventions_and_suggestions,
    test_set_filter_dispatch,
    test_clear_filter_dispatch,
    test_checkpoint_interval_validation,
    test_should_checkpoint_interval,
    test_compute_content_hash_dict,
    test_initialize_fresh_creates_directory,
    test_save_writes_checkpoint_file,
    test_save_metadata_content,
    test_validate_passes_when_all_match,
    test_validate_raises_on_hash_mismatch,
    test_validate_raises_on_strategy_mismatch,
    test_second_checkpoint_overwrites_first,
    test_load_raises_on_missing_checkpoint,
    test_load_raises_on_non_dict_checkpoint,
    test_load_raises_on_corrupt_checkpoint,
    test_validate_raises_on_missing_checkpoint,
    test_validate_raises_on_corrupt_checkpoint,
    test_validate_raises_on_non_dict_checkpoint,
    test_validate_raises_on_missing_metadata_key,
    test_validate_raises_on_invalid_metadata_type,
    test_validate_raises_on_missing_experiment_round,
    test_validate_raises_on_missing_target_permutations,
    test_validate_raises_on_missing_msq_state,
    test_validate_raises_on_missing_domain_state,
    test_validate_raises_on_invalid_msq_state_type,
    test_validate_raises_on_invalid_domain_state_type,
    test_param_domain_set_state_invalid_leaves_state_unchanged,
    test_param_domain_get_set_state,
    test_uel_shutdown_flag,
    test_uel_double_signal_raises,
    test_uel_checkpoint_and_resume,
    test_run_with_msq_basic_flow,
    test_run_with_msq_context_params,
    test_run_with_msq_feedback_trigger,
    test_run_with_msq_checkpoint_trigger,
    test_prep_output_ml_path,
    test_rule_based_prep_output_returns_full_dataframes,
    test_num_trades_counts_entries_not_bars,
    test_position_rate,
    test_backtest_metrics_flattened_with_split_suffix,
    test_sharpe_std_and_drawdown_std,
    test_sharpe_degradation,
    test_is_stable_true_when_within_thresholds,
    test_is_stable_false_when_sharpe_std_exceeds_threshold,
    test_missing_backtest_results_degrade_gracefully,
    test_with_strategy_sets_sentinel_and_returns_self,
    test_prepare_data_rule_based_returns_split_dataframes,
    test_prepare_data_rule_based_adds_predicate_columns,
    test_prepare_data_rule_based_attaches_strategy_config,
    test_prepare_data_rule_based_compound_condition_not_added_as_column,
    test_prepare_data_rule_based_rejects_scaler,
    test_prepare_data_rule_based_rejects_ablation,
    test_prepare_data_rule_based_rejects_condition_id_colliding_with_column,
    test_threshold,
    test_relative,
    test_crossover_above,
    test_crossover_below,
    test_slope_rising,
    test_slope_falling,
    test_with_persistence,
    test_with_recency,
    test_sql_expr_escape_hatch,
    test_build_predicate_threshold_with_param_substitution,
    test_build_predicate_unknown_type_raises,
    test_threshold_unknown_operator_raises,
    test_sql_expr_missing_param_raises,
    test_rule_based_config_cycle_detection,
    test_rule_based_config_operands_must_be_list,
    test_rule_based_config_operand_elements_must_be_strings,
    test_standard_run_csv_round_trips_special_string_fields,
    test_standard_run_csv_does_not_append_duplicate_headers_on_rerun,
    test_standard_run_csv_uses_experiment_dir,
    test_standard_run_rechunks_live_log_without_changing_row_output,
    test_execute_test_suite_writes_profile_and_stops_on_first_failure,
    test_runtime_gate_writes_summary_and_passes_when_within_budget,
    test_runtime_gate_fails_when_profile_exceeds_budget,
    test_checkpoint_saves_feedback_and_pruning_state,
    test_run_with_msq_shutdown_resume_full_data,
    test_run_with_msq_shutdown_resume_grid,
    test_shutdown_before_any_round_completes,
    test_resume_fails_without_round_data,
    test_preds_none_does_not_crash,
    test_resume_truncates_stale_rounds,
    test_truncate_round_data_unit,
    test_experiment_parameter_correlation_keeps_numeric_signal_columns_and_orders_cohorts,
    test_experiment_parameter_correlation_validates_metric_and_sort_key_presence,
    test_experiment_parameter_correlation_requires_numeric_features_after_cleaning,
    test_experiment_parameter_correlation_rejects_logs_without_metric_rows,
    test_uel_test_mode_routes_to_test_data_source,
    test_nan_above_threshold,
    test_early_returns,
    test_min_observations_gate,
    test_multiple_params_pruned,
    test_dedup_across_triggers,
    test_boundary_exact_threshold,
    test_zero_metric_suggestion,
    test_zero_metric_disabled_by_default,
    test_execution_timeout_suggestion,
    test_warning_suggestion,
    test_warning_no_column,
    test_suggestion_dedup,
    test_suggestion_checkpoint_roundtrip,
    test_wrong_direction_removal,
    test_low_impact_suggestion,
    test_corr_dedup_across_triggers,
    test_corr_early_returns,
    test_insufficient_data_for_correlation,
    test_corr_state_roundtrip,
    test_corr_set_state_missing_key,
    test_maximize_false,
    test_sign_stability_below_threshold,
    test_saturated_value_filter,
    test_no_saturation,
    test_sat_early_returns,
    test_window_size,
    test_zero_mean_skipped,
    test_unsaturation_clears_filter,
    test_sat_state_roundtrip,
    test_sat_set_state_missing_key,
    test_sat_constructor_validation,
    test_breakthrough_activates_focus,
    test_no_breakthrough,
    test_focus_maximize_false,
    test_focus_early_returns,
    test_snap_back_after_timeout,
    test_improvement_resets_timeout,
    test_numeric_narrowing_range,
    test_categorical_narrowing,
    test_zero_center_narrowing,
    test_variation_injection_count,
    test_variation_injection_linspace,
    test_no_injection_on_improvement,
    test_focus_mixed_param_types,
    test_improvement_updates_combo,
    test_focus_state_roundtrip,
    test_focus_set_state_missing_key,
    test_budget_constructor_validation,
    test_budget_early_returns,
    test_trimmed_flag_prevents_retrim,
    test_permutation_budget_trim_random,
    test_permutation_budget_check_after_pct_gate,
    test_walltime_budget_trim,
    test_walltime_exceeded,
    test_no_trim_when_within_budget,
    test_worst_first_trim,
    test_worst_first_fallback_to_random,
    test_remaining_none_with_permutation_budget,
    test_walltime_zero_elapsed,
    test_worst_first_includes_trim_fallback,
    test_both_budgets_takes_min,
    test_no_budget_configured,
    test_budget_state_roundtrip,
    test_budget_set_state_missing_key,
    test_worst_first_maximize_false,
    test_large_param_space,
    test_sample_range_exact_matches_stdlib_and_preserves_rng_state,
    test_sample_range_exact_retries_rejected_and_duplicate_draws_in_order,
    test_sample_range_exact_handles_edge_cases,
    test_sample_range_exact_skips_small_range_fallback_above_sys_maxsize,
    test_sample_range_exact_preserves_prefix_for_huge_ranges,
    test_param_space_small_legacy_sequence_is_unchanged,
    test_param_space_enumerates_full_space_and_returns_none_when_exhausted,
    test_param_space_large_space_no_longer_overflows_and_is_reproducible,
    test_param_space_large_space_sequences_match_for_both_generation_modes,
    test_klines_data_maker_fields,
    test_volume_bars_basic,
    test_trade_bars_basic,
    test_liquidity_bars_basic,
    test_compute_data_bars_base_and_unknown_modes_return_input_unchanged,
    test_compute_data_bars_dispatches_to_specific_bar_builders,
    test_compute_data_bars_requires_threshold_for_selected_bar_type,
    test_pre_split_random_selector,
    test_foundational_sfd,
    test_conserved_flux_renormalization,
    test_calibrate_confidence_threshold,
    test_apply_confidence_filtering,
    test_confidence_filtering_system,
    test_edge_cases,
    test_account_conviction,
    test_backtest_conviction,
    test_rdop,
    test_offline_filter_sanity_filter_drops_rows_with_null_performance_values,
    test_offline_filter_outlier_filter_removes_extreme_iqr_outlier,
    test_offline_regime_cluster_models_returns_single_cluster_for_one_sample,
    test_offline_regime_cluster_models_limits_cluster_count_to_sample_size,
    test_offline_diversification_returns_input_when_already_at_target_count,
    test_offline_diversification_selects_unique_models_up_to_target_count,
    test_online_model_loader_extract_model_params_excludes_perf_and_metadata_columns,
    test_online_model_loader_merge_prediction_dataframes_joins_on_price_keys,
    test_aggregation_strategy_supports_mean_median_majority_vote_and_fallback,
    test_online_aggregation_run_regime_experiments_skips_failed_models_and_drops_prediction_columns,
    test_rdop_offline_pipeline_handles_all_null_metrics_as_single_regime,
    test_rdop_online_pipeline_returns_empty_frame_when_no_regime_produces_predictions,
    test_rdop_online_pipeline_attaches_prediction_columns_for_each_regime,
    test_get_any_file_loads_local_csv,
    test_get_spot_klines_reaggregates_latest_dataset,
    test_get_spot_klines_rejects_sub_base_intervals,
    test_resolve_file_path_or_url_expands_huggingface_references,
    test_get_any_file_loads_zipped_csv_and_derives_datetime_from_timestamp,
    test_get_any_file_validates_requested_row_count_and_column_names,
    test_get_any_file_rejects_unsupported_extensions,
    test_get_spot_klines_accepts_iso_start_dates_and_rejects_invalid_literals,
    test_indicators_vs_talib,
    test_xgboost_train_returns_fitted_model,
    test_xgboost_evaluate_returns_all_metric_types,
    test_logreg_train_evaluate_end_to_end,
    test_random_binary_train_evaluate_end_to_end,
    test_tabpfn_train_evaluate_end_to_end,
    test_train_with_validation_data,
    test_train_without_validation_data,
    test_rule_based_train_is_noop,
    test_rule_based_evaluate_returns_expected_metrics,
    test_rule_based_is_stable_respects_thresholds,
    test_rule_based_function_returns_flat_dict,
    test_rule_based_or_compound_condition,
    test_rule_based_not_operator,
    test_rule_based_empty_operands_raises,
    test_rule_based_unknown_operator_raises,
    test_price_data_for_backtest_has_ohlc_columns,
    test_price_data_for_backtest_row_count_matches_test,
    test_price_data_for_backtest_datetime_alignment,
    test_shifted_target_pipeline_keeps_price_rows_on_feature_bar,
    test_logreg_manifest_keeps_price_rows_on_the_feature_bar,
    test_override_split_config,
    test_override_data_source_param,
    test_override_multiple_params,
    test_override_param_not_in_original_but_in_signature,
    test_unknown_override_key_raises,
    test_inline_and_post_experiment_metrics,
    test_logreg_inline_and_post_confusion_metrics_match,
    test_xgboost_inline_and_post_backtest_metrics_match,
    test_backtest_snapshot_executes_on_next_bar,
    test_backtest_snapshot_preserves_shifted_hold_while_one_continuation,
    test_backtest_snapshot_applies_costs_multiplicatively_per_fill,
    test_backtest_snapshot_drawdown_includes_starting_equity_peak,
    test_backtest_snapshot_drops_predictions_without_immediate_next_execution_bar,
    test_completed_bar_signal_proves_next_bar_alignment,
    test_backtest_snapshot_rejects_empty_input,
    test_backtest_snapshot_rejects_inconsistent_price_change,
    test_backtest_snapshot_rejects_missing_predictions,
    test_backtest_snapshot_rejects_non_binary_predictions,
    test_backtest_snapshot_rejects_non_numeric_price_values,
    test_experiment_backtest_results_directionalizes_regression_predictions,
    test_permutation_confusion_metrics_adds_mean_return_pct_columns,
    test_permutation_confusion_metrics_keeps_mean_returns_on_unfiltered_rows,
    test_permutation_confusion_metrics_uses_positional_alignment_for_returns,
    test_permutation_confusion_metrics_requires_return_columns,
    test_prepare_snapshot_backtest_input_rejects_multiclass,
    test_prepare_snapshot_backtest_input_rejects_non_numeric_logged_values,
    test_read_from_file_matches_full_header_and_keeps_non_header_recall_rows,
    test_read_from_file_removes_duplicate_headers_and_trims_object_columns,
    test_atr_sma_matches_manual_true_range_average,
    test_atr_percent_sma_scales_atr_by_close,
    test_close_position_uses_intra_candle_range,
    test_distance_features_use_rolling_highs_and_lows,
    test_gap_high_uses_previous_close,
    test_price_range_position_tracks_close_within_rolling_channel,
    test_trend_strength_uses_fast_and_slow_moving_average_divergence,
    test_volume_ratio_builds_missing_baseline_sma,
    test_volume_ratio_respects_existing_baseline_column,
    test_volume_regime_compares_recent_volume_to_longer_average,
    test_ichimoku_cloud_builds_shifted_components,
    test_sma_crossover_marks_bullish_and_bearish_crosses,
    test_close_to_extremes_reports_relative_distance_to_high_and_low,
    test_dynamic_stop_loss_clips_volatility_adjusted_levels,
    test_dynamic_target_clips_volatility_adjusted_targets,
    test_exit_quality_distinguishes_good_bad_and_neutral_exits,
    test_log_returns_uses_log_ratio_of_consecutive_prices,
    test_micro_momentum_uses_period_pct_change,
    test_momentum_weight_only_boosts_positive_momentum,
    test_position_in_range_matches_candle_fraction_formula,
    test_regime_multiplier_maps_low_normal_and_high_regimes,
    test_spread_and_spread_percent_match_same_ratio,
    test_calendar_time_features_extract_discrete_fields,
    test_cyclical_time_features_extract_sine_and_cosine_fields,
    test_volatility_1h_copies_requested_source_column,
    test_volatility_measure_averages_rolling_volatility_and_atr_percent,
    test_ema_alignment_adds_ema_and_alignment_score,
    test_position_in_candle_matches_range_fraction,
    test_risk_reward_ratio_uses_absolute_drawdown_with_epsilon_guard,
    test_volume_spike_supports_ratio_and_zscore_modes,
    test_breakout_percentile_regime_labels_up_flat_and_down,
    test_window_return_regime_labels_positive_negative_and_neutral_windows,
    test_range_based_volatility_estimators_match_constant_ratio_bars,
    test_yang_zhang_volatility_handles_zero_overnight_jumps_and_rejects_tiny_windows,
    test_liquidity_features_match_manual_ohlcv_impact_formulas,
    test_return_per_dollar_volume_and_amihud_handle_zero_dollar_volume_with_epsilon_guard,
    test_realized_semivariance_separates_upside_and_downside_return_energy,
    test_realized_skewness_and_kurtosis_match_manual_standardized_moments,
    test_jump_variation_proxy_matches_manual_realized_minus_bipower_component,
    test_jump_variation_proxy_returns_null_when_window_cannot_form_bipower_pairs,
    test_tail_event_intensity_lights_up_after_repeated_large_shocks,
    test_volatility_of_volatility_matches_nested_sample_standard_deviation,
    test_relative_volume_and_range_seasonality_compare_against_same_hour_of_week_history,
    test_relative_volatility_seasonality_uses_same_hour_of_week_absolute_returns,
    test_candle_structure_features_capture_body_wicks_overlap_and_rejection,
    test_trend_coherence_scores_full_and_partial_directional_agreement,
    test_volatility_term_structure_matches_manual_front_vs_back_ratio_average,
    test_feature_aliases_fill_nulls_and_build_regime_aliases,
    test_feature_aliases_can_skip_regime_aliases,
    test_returns_lags_builds_returns_when_missing,
    test_returns_lags_respects_existing_returns_column,
    test_volume_weight_uses_clipped_ratio_to_volume_average,
    test_momentum_confirmation_combines_short_and_long_signals,
    test_momentum_confirmation_rejects_invalid_period_order,
    test_volatility_weight_inversely_scales_rolling_volatility,
    test_momentum_periods_adds_requested_period_columns,
    test_volume_trend_compares_short_and_long_volume_averages,
    test_entry_score_microstructure_switches_weights_by_regime,
    test_ema_breakout_labels_future_moves_above_ema_threshold,
    test_hh_hl_structure_regime_detects_up_flat_and_down_windows,
    test_ma_slope_regime_uses_sma_slope_direction,
    test_price_vs_band_regime_flags_prices_outside_rolling_bands,
    test_active_lines_counts_overlapping_long_and_short_spans,
    test_active_lines_returns_zero_when_no_lines_or_rows_exist,
    test_active_quantile_count_tracks_quantile_filtered_spans,
    test_quantile_line_density_counts_recent_line_endings_within_lookback,
    test_market_regime_keeps_parameterized_smas_and_adds_normalized_aliases,
    test_ema_segment_returns_empty_when_requested_range_is_before_lookback,
    test_ema_segment_matches_manual_recursive_values,
    test_default_ema_segment_uses_standard_talib_constant,
    test_stddev_from_var_matches_manual_rolling_std_and_returns_empty_before_lookback,
    test_stddev_using_precalc_ma_matches_manual_window_std,
    test_ht_phasor_short_inputs_return_nan_only_and_wrapper_uses_custom_price_col,
    test_ht_phasor_constant_signal_stays_zero_after_lookback_and_matches_wrapper,
    test_ht_phasor_oscillating_signal_produces_distinct_components,
    test_ht_sine_short_inputs_return_nan_only_and_wrapper_outputs_bounded_values,
    test_ht_sine_constant_signal_converges_to_stable_bounded_outputs,
    test_ht_sine_oscillating_signal_matches_wrapper_and_has_phase_advanced_lead,
    test_price_change_pct_computes_percentage_change_from_prior_close,
    test_returns_matches_polars_pct_change_convention,
    test_rsi_sma_is_neutral_when_recent_gains_and_losses_balance,
    test_random_slice_rejects_invalid_safe_range_bounds,
    test_random_slice_rejects_slice_that_cannot_fit_safe_range,
    test_random_slice_returns_contiguous_window_inside_safe_range,
    test_split_sequential_preserves_order_and_uses_all_rows,
    test_split_random_creates_reproducible_partition_with_full_coverage,
    test_split_data_to_prep_output_builds_expected_alignment_metadata,
    test_split_data_to_prep_output_requires_datetime_column,
    test_data_dict_to_numpy_converts_requested_polars_entries,
    test_data_dict_to_numpy_respects_custom_keys_and_preserves_numpy_values,
    test_permutation_prediction_performance_preserves_inverse_scaled_features,
    test_permutation_prediction_performance_falls_back_to_single_argument_prep,
    test_multiclass_metrics_returns_expected_rounded_summary,
    test_balanced_metric_returns_zero_without_positive_predictions,
    test_balanced_metric_penalizes_sparse_precision_by_trade_rate,
    test_reporting_helpers_honor_requested_width_and_titles,
    test_mad_transform_scales_around_column_median_and_preserves_context_columns,
    test_zscore_transform_centers_numeric_values_and_guards_constant_columns,
    test_winsorize_transform_clips_extreme_tail_values,
    test_quantile_trim_transform_removes_tail_rows_and_preserves_nulls,
    test_numeric_transforms_leave_non_numeric_frames_unchanged,
    test_sklearn_probability_calibrator_no_future_warning,
    test_grid_threshold_optimizer_picks_best_balanced_threshold,
    test_grid_threshold_optimizer_returns_default_when_all_thresholds_predict_zero,
    test_grid_threshold_optimizer_returns_bounded_threshold,
    test_calibration_config_resolve_substitutes_string_params,
    test_calibration_builder_done_raises_without_any_func,
    test_run_model_injects_resolved_prediction_calibration_config,
    test_run_model_no_injection_when_calibration_not_set,
    test_run_model_no_injection_when_both_flags_false,
    test_run_model_masks_calibration_func_when_use_calibration_false,
    test_run_model_masks_threshold_func_when_use_threshold_false,
    test_logreg_predict_without_calibration_unchanged,
    test_logreg_predict_threshold_only_returns_threshold_keys,
    test_add_indicator_creates_transform_entry,
    test_feature_group_filtering_includes_selected,
    test_feature_group_filtering_multiple_groups,
    test_feature_group_absent_includes_all,
    test_combined_group_and_include_if,
    test_include_if_true,
    test_include_if_false,
    test_include_if_key_missing_includes,
    test_ablation_drops_correct_count,
    test_ablation_deterministic_with_seed,
    test_ablation_zero_drops_nothing,
    test_ablation_preserves_datetime_and_target,
    test_ablation_consistent_across_splits,
    test_ungrouped_features_always_included,
    test_ablation_not_configured_noop,
    test_feature_groups_all_includes_everything,
    test_ablation_invalid_drop_count_raises,
    test_robust_scaler_fit_and_transform,
    test_robust_scaler_custom_quantile_range,
    test_robust_scaler_zero_iqr_guard,
    test_robust_scaler_preserves_datetime,
    test_robust_scaler_outlier_resilience,
    test_rank_gauss_output_approximately_normal,
    test_rank_gauss_preserves_rank_order,
    test_rank_gauss_handles_unseen_values,
    test_rank_gauss_preserves_datetime,
    test_rank_gauss_constant_column,
    test_rank_gauss_integer_column,
    test_robust_scaler_all_null_column,
    test_robust_scaler_inverse_transform,
    test_rank_gauss_inverse_transform,
    test_robust_scaler_invalid_quantile_range,
    test_rank_gauss_invalid_n_quantiles,
    test_scaler_factory_selects_all_types,
    test_scaler_factory_unknown_raises,
    test_scaler_factory_registry_has_all,
    test_quantile_binary_fits_cutoff_on_train,
    test_quantile_binary_transform_labels_above_cutoff,
    test_quantile_binary_shift_applied_when_nonzero,
    test_forward_breakout_labels_above_threshold,
    test_forward_breakout_shift_applied,
    test_threshold_binary_labels_above_threshold,
    test_threshold_binary_threshold_is_fixed,
    test_threshold_binary_shift_applied,
    test_next_return_computes_percentage_return,
    test_next_return_respects_periods,
    test_next_return_respects_scale,
    test_with_target_label_sets_target_class_config,
    test_with_target_label_applies_transform_to_all_splits,
    test_with_target_label_fits_only_on_train,
    test_random_binary_target_adds_column_with_binary_values,
    test_identity_target_returns_data_unchanged,
    test_identity_target_raises_when_column_missing_on_init,
    test_identity_target_raises_when_column_missing_on_transform,
    test_ablation_drop_count_exceeds_eligible_raises,
    test_reducer_registry_has_all_types,
    test_reducer_registry_maps_to_correct_classes,
    test_reducer_registry_unknown_key_raises,
    test_random_basic_iteration,
    test_random_seeded_reproducibility,
    test_random_dedup_skips_seen,
    test_random_get_set_state,
    test_random_rebuild_seen_from_log,
    test_random_with_msq,
    test_injected_combo_registered_in_seen,
    test_random_on_domain_changed,
    test_random_large_domain,
    test_grid_exhaustive_small_space,
    test_grid_covers_full_space,
    test_grid_deterministic_order,
    test_grid_shuffle_covers_full_space,
    test_grid_shuffle_different_order,
    test_grid_shuffle_seeded_reproducibility,
    test_grid_get_set_state,
    test_grid_on_domain_changed,
    test_grid_large_space_shuffle,
    test_grid_with_msq,
    test_strategy_registry,
    test_param_hash_deterministic,
    test_param_hash_key_order_independent,
    test_param_hash_different_combos_differ,
    test_fractional_diff_d_zero_copies,
    test_fractional_diff_d_one_equals_first_diff,
    test_fractional_diff_weights_convergence,
    test_fractional_diff_preserves_original_columns,
    test_fractional_diff_cols_none_raises,
    test_fractional_diff_negative_d_raises,
    test_fractional_diff_lazyframe,
    test_adf_test_stationary_series,
    test_adf_test_nonstationary_series,
    test_find_min_d_returns_valid_d,
    test_fractional_diff_empty_dataframe,
    test_fractional_diff_missing_column_skips,
    test_adf_test_empty_series,
    test_adf_test_constant_series,
    test_find_min_d_step_zero_raises,
    test_find_min_d_small_data_skips,
    test_split_validation_rejects_invalid,
    test_column_consistency_drops_mismatched_columns,
    test_fractional_diff_manifest_integration,
    test_trainer_end_to_end,
    test_reconstruction_error_stochastic,
    test_reconstruction_error_tampered_log,
    test_deterministic_validation,
    test_pass2_uses_full_data,
    test_sensor_inference,
    test_trainer_with_feature_ablation,
    test_trainer_with_fractional_diff,
    test_load_round_data_skips_blank_and_malformed_lines,
    test_load_round_data_requires_round_data_file,
    test_load_original_log_returns_none_when_results_csv_is_missing,
    test_resolve_model_class_requires_configured_architecture_function,
    test_resolve_model_class_rejects_modules_without_reference_model_subclasses,
    test_resolve_model_class_rejects_modules_with_multiple_reference_model_subclasses,
    test_validate_metrics_ignores_metadata_fields_and_accepts_small_stochastic_drift,
    test_validate_metrics_reports_missing_permutations_and_large_deterministic_mismatches,
    test_rejects_when_no_source_provided,
    test_rejects_when_both_sources_provided,
    test_rejects_missing_experiment_log_path,
    test_defaults_to_all_permutations_when_not_provided,
    test_rejects_empty_permutation_ids,
    test_rejects_duplicate_permutation_ids,
    test_rejects_unknown_permutation_ids,
    test_accepts_string_permutation_ids_when_numeric,
    test_rejects_when_round_data_is_missing,
    test_rejects_unresolvable_experiment_id,
    test_rejects_ambiguous_experiment_id_resolution,
    test_rejects_mixed_architecture_selection,
    test_sets_probability_mode_for_probability_capable_architecture,
    test_sets_fallback_mode_for_non_probability_architecture,
    test_probability_weighted_predict_aggregates_mean_p1,
    test_probability_weighted_predict_single_member_matches_own_thresholded_probs,
    test_single_decoder_passthrough_returns_member_preds_unchanged,
    test_probability_weighted_predict_requires_members,
    test_predict_return_probs_probability_mode_returns_per_sample_probs,
    test_predict_return_probs_single_member_returns_sample_major_column,
    test_majority_vote_tie_returns_zero,
    test_probability_weighted_tie_returns_zero,
    test_majority_vote_multimember_expected_output,
    test_probability_weighted_vote_rejects_shape_mismatch,
    test_majority_vote_rejects_shape_mismatch,
    test_majority_vote_uses_binary_votes_for_continuous_fallback_members,
    test_single_member_fallback_predict_returns_binary_votes,
    test_predict_return_meta_returns_metadata_placeholder,
    test_predict_return_probs_and_return_meta_returns_three_tuple,
    test_predict_return_probs_rejected_in_fallback_mode,
    test_validate_probability_range_accepts_values_in_unit_interval,
    test_validate_probability_range_rejects_out_of_range_values,
    test_validate_probability_range_rejects_non_finite_values,
    test_cohort_is_drop_in_decoder_replacement_for_dict_input,
    test_member_failure_propagates_and_fails_whole_call,
]

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def _runtime_profile_output_path() -> Path | None:
    configured_path = os.getenv('LIMEN_RUNTIME_PROFILE_PATH')
    if configured_path:
        return Path(configured_path)

    if os.getenv('LIMEN_COVERAGE_RUN') or os.getenv('CI'):
        return Path('coverage-artifacts/test_runtime_profile.json')

    return None


def _runtime_slowest_tests_limit() -> int:
    configured_limit = os.getenv('LIMEN_RUNTIME_SLOWEST_LIMIT')
    if not configured_limit:
        return DEFAULT_SLOWEST_TESTS_LIMIT

    parsed_limit = int(configured_limit)
    if parsed_limit <= 0:
        raise ValueError('LIMEN_RUNTIME_SLOWEST_LIMIT must be a positive integer')

    return parsed_limit


def main() -> int:
    setup_cleanup_handlers()
    result = execute_test_suite(
        tests=tests,
        logger=logger,
        profile_output_path=_runtime_profile_output_path(),
        slowest_tests_limit=_runtime_slowest_tests_limit(),
    )

    cleanup_csv_files()

    if result.failure_traceback is not None:
        sys.stderr.write(result.failure_traceback)

    return result.exit_code


if __name__ == '__main__':
    raise SystemExit(main())
